### ISSUE TITLE
pip install -e .报错

### ISSUE THREAD

**Issue by Czi24** [zackschen/CoIN#1]
### Question

运行pip install -e .后，机器都访问不了网站了

Could not fetch URL https://mirrors.aliyun.com/pypi/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='[mirrors.aliyun.com](http://mirrors.aliyun.com/)', port=443): Max retries exceeded with url: /pypi/simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)'))) - skipping

**Comment by Czi24** [comment]
请问您遇到过吗，需要怎么解决

**Comment by zackschen** [comment]
这应该是源的问题吧？你换个源试试喃

**Comment by Czi24** [comment]
不是源的问题哈，两台机器pip install -e .这个仓库，都出问题了，都是报SSL的错误。不止是pip，curl也是，所有需要网络的都不行了。

您可以在一台新的机器试试，如果有解决方案，非常感激您。

curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by Czi24** [comment]
已解决，是实验室停网了
