### ISSUE TITLE
Some questions about experiment tables in paper [Question]

### ISSUE THREAD

**Issue by Minato-Zackie** [zackschen/CoIN#11]
Thanks a lot for your contribution!
我在阅读您的论文时，对于实验表格的数据有一些疑问：
1.在table2的fintune行中，第一行的结果是指每个任务在原始的llava预训练模型上微调的结果，还是经过前几个任务微调后，再对该任务微调后结果？例如：第2个任务TextVQA的结果是49.99，请问是在经过ScienceQA任务微调后的模型上再进行微调，还是直接在原始预训练模型上微调得出的结果呢？
2.有关BWT的结果，论文的公式上是除以（T-1），但表格中的结果似乎是除以（T），这两个地方是否有一定的出入？
以上是我对于表格数据的一些疑问，希望能得到您的解答！

**Comment by zackschen** [comment]
1. 是经过前几个任务微调后再对该任务微调后结果，比如TextVQA就是经过ScienceQA任务微调后的模型上再在TextVQA进行微调的结果。
2.论文中和实际计算确实是不一样，但是每个结果的BWT都经过相同的计算，所以是不影响横向对比的，我会后续修正这个问题。

**Comment by Minato-Zackie** [comment]
好的，非常感谢您的解答！
