### ISSUE TITLE
Code of MoELoRA

### ISSUE THREAD

**Issue by LiangJian24** [zackschen/CoIN#12]
Thanks for your new code! Is the new codebase compatible with the MoELoRA scripts from the old codebase?

**Comment by zackschen** [comment]
No. Actually, this version also maintains the MoELoRA code, I will add a script to use it as soon as possible.

**Comment by zackschen** [comment]
I have uploaded a new version that contains the scripts to train MOELoRA, you can try it.
If you still have any question, please let me know.

**Comment by LiangJian24** [comment]
Thanks for your great work!

**Comment by kailinjiang** [comment]
When using the MOE training code, I encountered the following problems
from peft.utils.config import PeftConfig, PeftType
ModuleNotFoundError: No module named 'peft.utils.config'

It seems to be a **peft** version problem. I would like to ask about your version

**Comment by zackschen** [comment]
I have uploaded the version of the libraries in requirements.txt. You could change your version to these to validate.
