### ISSUE TITLE
pid_split.json

### ISSUE THREAD

**Issue by HaoranChen** [zackschen/CoIN#14]
Thanks for the work! Regarding the evaluation process, it seems that a pid_split.json file is needed. Where can I find this file?

**Comment by zackschen** [comment]
Hello,
Do you conduct evaluations on ScienceQA? 
You can find this file in the ScienceQA dataset with this [link](https://drive.google.com/drive/folders/1w8imCXWYn2LxajmGeGH_g5DaL2rabHev).
If you still have problems, please let me know.

**Comment by HaoranChen** [comment]
Thanks for the help!
