### ISSUE TITLE
关于imagenet数据集[Question]

### ISSUE THREAD

**Issue by Leo-Yuyang** [zackschen/CoIN#15]
您好，非常感谢您的工作！对于imagenet数据集，我发现您readme中给出的链接是imagenet官网，但是官网上有10~17八个不同的数据集，我想了解一下我具体应该下载哪个呀？我看测试集里有带有2012的数据，请问是下载2012这个版本即可嘛？谢谢解答~
![image](https://github.com/user-attachments/assets/ea5bf863-8191-4bcd-aec8-4a935c1d80e1)

**Comment by Leo-Yuyang** [comment]
或者您是否方便将用到的训练和验证集图片压缩git lfs传到huggingface上并提供一个链接？这样对于我们社区用户会更方便，因为用到的只是一个子集，而我们现在需要下载一百多g的imagenet全集，并且没有直接给出下载链接，使用起来稍微有些麻烦~

**Comment by zackschen** [comment]
嗯嗯，好的，我会将使用的imagenet的图片筛选出来打包，目前链接在：[OneDrive](https://stduestceducn-my.sharepoint.com/:u:/g/personal/chen_cheng_std_uestc_edu_cn/ESJULLsNiIpFserUr1yhCa0B7Y_vwxawMPv9prsnO9Yrlg?e=biqKIv)。你可能需要下载之后将文件夹名字改为ImageNet_withlabel。
如果有问题请再联系我。

**Comment by kaln27** [comment]
@zackschen 谢谢你分享的数据集，但是我下载的时候显示是 14GB 但是下载下来就 12GB，并且在解压的过程中也报了错 

<img width="630" height="82" alt="Image" src="https://github.com/user-attachments/assets/80b13bb1-c556-4b60-9554-761182fa4f88" />

在 eval 的时候也发现少了图片，训练的图片是完备的。
能不能更新一下这个 imagenet 下载的链接呢？谢谢🙏

**Comment by kaln27** [comment]
> [@zackschen](https://github.com/zackschen) 谢谢你分享的数据集，但是我下载的时候显示是 14GB 但是下载下来就 12GB，并且在解压的过程中也报了错
> 
> <img alt="Image" width="630" height="82" src="https://private-user-images.githubusercontent.com/86989360/500102548-80b13bb1-c556-4b60-9554-761182fa4f88.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjAxOTk0NTYsIm5iZiI6MTc2MDE5OTE1NiwicGF0aCI6Ii84Njk4OTM2MC81MDAxMDI1NDgtODBiMTNiYjEtYzU1Ni00YjYwLTk1NTQtNzYxMTgyZmE0Zjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDExVDE2MTIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzN2NhYzA4ZmExYjEzZDU3NmEyMjM4NWVkY2VhYzMxY2EwNDNkNGQ1NTUwYTA1NTQ4YmU3ZjE3Nzg5NjlmNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ABiu5Nwh-HotwVCFKlz7HjZNLYBYBkQ0pv272dVnZQw">
> 在 eval 的时候也发现少了图片，训练的图片是完备的。 能不能更新一下这个 imagenet 下载的链接呢？谢谢🙏

是我这边网络问题，你上传的数据集没问题 😂
