### ISSUE TITLE
invalid link of refcoco, refcocoplus, refcocog

### ISSUE THREAD

**Issue by Leo-Yuyang** [zackschen/CoIN#16]
您好，您给出的三个refcoco链接均无法打开，并且我理解instruction只需要用到图片和对应的instruction就行，
![image](https://github.com/user-attachments/assets/a29e37aa-a5a2-4df6-a464-e76b717049a4)
您这里也说的是下载图片，可是下面链接的地方又是说下载annotation, 我比较困惑这里的链接到底是图片还是annotation?

如果我理解正确，是不是只需要下载coco2014配上您给出的instruction即可使用，如果是这样，那么这里无效的annotation链接是什么作用呢？如果不是我想的这样，求问具体应该如何使用refcoco相关的instruction呀？是refcoco这样的任务用到的不是coco2014里的图片，而是需要在另一个地方下载别的图片嘛？如果是这样，求更新一下链接，谢谢您的工作~

**Comment by Leo-Yuyang** [comment]
![image](https://github.com/user-attachments/assets/29765c8c-270b-4bf4-ae1a-66262b930cbb)

**Comment by zackschen** [comment]
使用COCO2014的图片就行。
这里提供annotation是如果有人需要进行更改或者观看原始数据的需要。
链接无效是原来该的作者停止了分享，如果你不需要进行数据更改或其他操作，直接使用COCO2014进行训练进行。

**Comment by Leo-Yuyang** [comment]
感谢您的解答~
