### ISSUE TITLE
Qwen zero shot

### ISSUE THREAD

**Issue by chanceche** [zackschen/CoIN#18]
![Snipaste_2024-10-28_19-57-31](https://github.com/user-attachments/assets/9ec76084-68df-4f93-b48d-85e74a93edaf)
作者你好，我使用Qwen在textvqa上测zero_shot的结果很低，请问使用的是Qwen-vl-chat吗，还是什么其他的问题

**Comment by zackschen** [comment]
嗯嗯，我使用的是Qwen-vl-chat，这个在训练和测试的脚本里面写了的

**Comment by chanceche** [comment]
哦哦，恭喜你中了nips啊，我现在在复现代码，然后在qwen上指令微调的时候发现效果很差，请问训练和测试的脚本是有更改吗？这个qwen的textvqa的zero_shot为什么我跑出来这么低呀

**Comment by zackschen** [comment]
你是用的Qwen-vl-chat吗？脚本没有改动啊？我就只是把我的路径什么的改动过。
![image](https://github.com/user-attachments/assets/b40f2856-6ed0-4d59-9d08-ad377bee4205)
而且，Zero-shot不是还没训练吗？其他数据集的测试效果有差距很大吗？

**Comment by chanceche** [comment]
使用的是qwen-vl-chat啊，使用的也是你开源的指令微调数据集更改了训练集的格式，但是question和instruction都没变动，顺序微调到textvqa时候，测试效果很差只有20多。然后测试了一下zero_shot也只有20多. 你使用的是什么测试的呀。textvqa的val集不是5000个sample吗

**Comment by zackschen** [comment]
我这个是只是随便截的结果，使用不同样本量的，恰好4000和5000的结果四舍五入是一样的。
那你微调ScienceQA的效果咋样喃？或者你直接Zero其他数据集的效果喃？

**Comment by chanceche** [comment]
微调ScienceQA的跟论文差不多，就是训到TextVQA出入有点大只有22。后面就没继续训了。zero的imagenet：25.64。gqa：36.74，也有点出入。不会是我用的模型不对吧。
![Snipaste_2024-10-28_21-06-47](https://github.com/user-attachments/assets/372dc4b4-a846-4dc6-b7b2-79e277a8bbcf)是这个qwen-vl-chat嘛？

**Comment by zackschen** [comment]
![image](https://github.com/user-attachments/assets/bbbe72c8-6a3c-44f6-90be-98cef4f4e9f7)
是下载的这个checkpoint把？那应该不会有问题啊？LLaVA的结果正常吗？

**Comment by chanceche** [comment]
llava正常的，头痛这个qwen哈哈

**Comment by chanceche** [comment]
超参我改了一下下，不过应该没问题吧，epoch 1 ，batchsize动了一下，其他都是默认的设置

**Comment by zackschen** [comment]
应该是没有影响的啊，你zero的效果又不受这些影响。
我看看你zero的script喃

**Comment by chanceche** [comment]
我把模型加载时候的加载lora部分去掉了，不就是只加载basemodel了嘛
![image](https://github.com/user-attachments/assets/b573a5a0-e13e-45d0-b262-0fe76343c79a)

![image](https://github.com/user-attachments/assets/6ca631f2-b577-48a1-bb83-c27bd231ec05)

**Comment by zackschen** [comment]
经过我们的检查，由于这个项目的前面使用过Qwen-vl和Qwen-vl-chat，致使代码现在有点乱，Qwen的结果可能有一定出入，你可以先以你自己的结果为准，我们后续会更新新结果

**Comment by chanceche** [comment]
好的好的，谢谢作者，辛苦了🌹

**Comment by zackschen** [comment]
@cc181209 你好，这是我们最新测试出来的结果，你可以参考下，代码也有一点点改动（load 模型和生成结果对比的地方）。
![image](https://github.com/user-attachments/assets/19a8bdf7-033e-4e94-9b96-e6062fbdcbfc)

**Comment by chanceche** [comment]
好的，请问用的是哪一阶段的模型呀

**Comment by zackschen** [comment]
哪个阶段是什么意思？Qwen-VL和Chat版的的都有

**Comment by chanceche** [comment]
哦哦，看到了代码的改动，我回头再试一下，感谢作者
