### ISSUE TITLE
Reasoning Capability的准确率是什么意思呀？

### ISSUE THREAD

**Issue by jinpeng0528** [zackschen/CoIN#19]
Hello～最近在基于CoIN做实验，想问一下Reasoning Capability的Accuracy是什么意思？因为我看这个Reasoning Capability是0-10的分数，那怎么会有准确率Accuracy呢？

另外就是我想知道你们是用了全部test set得出的Reasoning Capability吗？因为我看论文里写的Reasoning Capability的准确率百分比都是整数，所以推测是不是只选了100个样本算Reasoning Capability？

期待你的回复，谢谢！

**Comment by zackschen** [comment]
你好
第一个ACC问题：每个样本是0-10的分数，然后，比如100个样本加起来的分数（900），除以100个样本的总分数（100*10），那这个ACC就是90。
第二个问题：使用的是全部的test set，只是取整了。

**Comment by jinpeng0528** [comment]
明白啦，非常感谢！
