### ISSUE TITLE
请教专家个数设置问题

### ISSUE THREAD

**Issue by Czi24** [zackschen/CoIN#2]
### Question

<img width="416" alt="截屏2024-04-10 22 34 12" src="https://github.com/zackschen/CoIN/assets/164003022/bf06f3c6-a50f-4786-8895-88e693736d18">

task_num表示专家模型的个数吗？

看到您没有放上zero_offload.json文件，是不是跟llava一样呢？

**Comment by zackschen** [comment]
expert_num 才是代表的专家数量，task_num 当时有其他作用。
嗯嗯，可以直接使用llava的zero_offload.json
