### ISSUE TITLE
GPU和显存

### ISSUE THREAD

**Issue by tenderzada** [zackschen/CoIN#3]
### Question

非常感谢你们提供的研究成果，读完深受启发。请问复现你们的工作需要多少计算资源，GPU的显存，内存等的大致需求是多少？

**Comment by zackschen** [comment]
我们使用的是3090显卡和4090显卡，24G显存，机器的内存是256G的。

**Comment by tenderzada** [comment]
> 我们使用的是3090显卡和4090显卡，24G显存，机器的内存是256G的。

感谢回复，我们正好有类似的资源~~
