### ISSUE TITLE
关于imagenet数据集[Question] 

### ISSUE THREAD

**Issue by LiangJian24** [zackschen/CoIN#4]
### Question

非常感谢您的开源代码！请问imagenet数据集是您随机取的100个类别的子集吗？根据您给出的Instructions_Type1/ImageNet/train.json文件，里面有129833张图片的instructions，这似乎和论文中提到的117715张对应不上。

**Comment by zackschen** [comment]
嗯嗯，由于资源限制，我们不能接受训练全量的ImageNet数据集。我们做了一个消融实验，随机取100个类别和每个类别取一定数量和全量的效果相差不大。因此在后续我们均使用的100类别进行训练，类似于ImageNet-100数据集。

**Comment by LiangJian24** [comment]
> 嗯嗯，由于资源限制，我们不能接受训练全量的ImageNet数据集。我们做了一个消融实验，随机取100个类别和每个类别取一定数量和全量的效果相差不大。因此在后续我们均使用的100类别进行训练，类似于ImageNet-100数据集。

谢谢！
