### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Sequential:

### ISSUE THREAD

**Issue by Parinema** [zackschen/CoIN#5]
### Question

Could you please advise on resolving the error I encountered while following the steps in the GitHub repository? I downloaded the [liuhaotian/llava-v1.5-7b](https://huggingface.co/liuhaotian/llava-v1.5-7b) checkpoints and the Projector weights  [Vicuna-7B-v1.5](https://huggingface.co/liuhaotian/llava-v1.5-mlp2x-336px-pretrain-vicuna-7b-v1.5) and specified the path in the 'Science.sh' script. However, upon execution, I encountered an error, which I have attached a screenshot of the error. How can I resolve this issue? Additionally, could you clarify which projector file and model checkpoint I should download from the  [LLaVA Model_Zoo](https://github.com/haotian-liu/LLaVA/blob/main/docs/MODEL_ZOO.md)?
![Screenshot](https://github.com/zackschen/CoIN/assets/166944131/20afd4d7-daba-48ca-a492-0e70fa3a3db2)

**Comment by zackschen** [comment]
Actually, the llava-v1.5-7b is the instruction-tuned model, if you want to tune this model, you should not add the "pretrain_mm_mlp_adapter" parameter.
In our paper, we tune the pre-trained model, you just need to specify the LLM (vicuna 1.5) and the "pretrain_mm_mlp_adapter", instead of the "llava-v1.5-7b". I think the Projector weight you used is the same as us, the error is not from here.

**Comment by Parinitanema** [comment]
I am trying to reproduce the code. The script science.sh specifies:

--model_name_or_path checkpoints/Vicuna/vicuna-7b-v1.5 \
--pretrain_mm_mlp_adapter ./checkpoints/Vicuna/mm_projector.bin \ 

However, I am having trouble finding the Vicuna 1.5 model checkpoint for download. I have checked the [LLaVA Model_Zoo](https://github.com/haotian-liu/LLaVA/blob/main/docs/MODEL_ZOO.md), but I am unclear about which specific model checkpoints I should download.             
Could you please provide guidance on where to find the Vicuna 1.5 model and the necessary checkpoints? Any additional information for running the science.sh script would also be greatly appreciated.

**Comment by Parinema** [comment]
I am trying to reproduce the code. The script science.sh specifies:

--model_name_or_path checkpoints/Vicuna/vicuna-7b-v1.5
--pretrain_mm_mlp_adapter ./checkpoints/Vicuna/mm_projector.bin \

However, I am having trouble finding the Vicuna 1.5 model checkpoint for download. I have checked the [LLaVA Model_Zoo](https://github.com/haotian-liu/LLaVA/blob/main/docs/MODEL_ZOO.md), but I am unclear about which specific model checkpoints I should download.
Could you please provide guidance on where to find the Vicuna 1.5 model and the necessary checkpoints? Any additional information for running the science.sh script would also be greatly appreciated.

**Comment by zackschen** [comment]
There is no Vicuna 1.5 checkpoint url in LLaVA model_zoo, you could search and download it from huggingface [Vicuna-7b-v1.5](https://huggingface.co/lmsys/vicuna-7b-v1.5). Or you could just specify the "lmsys/vicuna-7b-v1.5" for "model_name_or_path", the code will download it automatically.
Is your "./checkpoints/Vicuna/mm_projector.bin" the [llava-v1.5-mlp2x-336px-pretrain-vicuna-7b-v1.5](https://huggingface.co/liuhaotian/llava-v1.5-mlp2x-336px-pretrain-vicuna-7b-v1.5). If it is, it's all right.

**Comment by Parinema** [comment]
Thank you for your guidance on resolving the previous issue; your solution worked perfectly. However, I've encountered a new error which I'm unable to resolve. I've attached a screenshot of the error message for your reference.
Could you please provide some assistance on how to address this new error?
![training error](https://github.com/zackschen/CoIN/assets/166944131/7c709cb1-1b0c-40a4-9926-2ba0c823f881)
