### ISSUE TITLE
Questions about task_num？

### ISSUE THREAD

**Issue by 45632219** [zackschen/CoIN#6]
### feature

Hello, I have a few questions to ask.
1. What is the task_num setting in CoIN, is it 16 or 2 by default? In the MOELoRA-peft paper, the setting is the number of multitasks, so it is set to 8.
2. Can you explain the role of task_num in CoIN?
3. The dimension of lora is 64, why is it set to 64?

Thanks!

**Comment by zackschen** [comment]
Hello, For the question:
1 & 2. The task_num was used the same as the MOELoRA-peft paper. But now, since we do not hold the input embeddings, it is deprecated. I will delete it in the next commit.
3. We just use the default value of it as MOELoRA-peft paper.
