### ISSUE TITLE
关于playground/create_prompt.py文件[Question] 

### ISSUE THREAD

**Issue by YuTinH** [zackschen/CoIN#7]
### Question

您好，请问在eval.sh命令中出现的playground/create_prompt.py文件在哪里可以找到呢？

**Comment by zackschen** [comment]
Sorry, some files are ignored by the gitignore, I have uploaded these files and you can try running the scripts to create the prompt to evaluate the general knowledge.

**Comment by YuTinH** [comment]
Thank you for your reply. Where can I download TextVQA_0.5.1_val.json in 2_eval_textqa.sh?

**Comment by zackschen** [comment]
You can download it from LLaVA or  [TextVQA_0.5.1_val.json](https://dl.fbaipublicfiles.com/textvqa/data/TextVQA_0.5.1_val.json) and [image](https://dl.fbaipublicfiles.com/textvqa/images/train_val_images.zip).
