### ISSUE TITLE
missing file convert_gqa_for_eval.py

### ISSUE THREAD

**Issue by AuroraZengfh** [zackschen/CoIN#9]
### Describe the issue

Congratulations on your excellent work!

I am trying to reproduce the results of your work. It appears to miss convert_gqa_for_eval.py when evaluating eval_gqa.sh. Could you share the file?

**Comment by zackschen** [comment]
Sorry, it's my fault for forgetting to upload this file. You can download it from https://github.com/haotian-liu/LLaVA/blob/main/scripts/convert_gqa_for_eval.py. In addition, I will upload it in the next version.

**Comment by AuroraZengfh** [comment]
I found it. Thank you for your response!
